# Form implementation generated from reading ui file 'Busqueda.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pandas as pd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(33, 84, 137, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 20, 361, 20))
        self.label.setStyleSheet("border-radius:10px")
        self.label.setObjectName("label")
        self.le_nombre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_nombre.setGeometry(QtCore.QRect(230, 90, 161, 20))
        self.le_nombre.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:10px")
        self.le_nombre.setObjectName("le_nombre")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 121, 20))
        self.label_2.setStyleSheet("border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 210, 161, 23))
        self.pushButton.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(63, 144, 182, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 470, 91, 23))
        self.pushButton_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(63, 144, 182, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius:10px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 470, 101, 23))
        self.pushButton_3.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(63, 144, 182, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius:10px")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 170, 451, 31))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 127);")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(90, 240, 611, 192))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pb_guardar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_guardar.setGeometry(QtCore.QRect(340, 470, 161, 23))
        self.pb_guardar.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(63, 144, 182, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius:10px")
        self.pb_guardar.setObjectName("pb_guardar")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 130, 121, 20))
        self.label_4.setStyleSheet("border-radius:10px")
        self.label_4.setObjectName("label_4")
        self.le_nombre_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_nombre_2.setGeometry(QtCore.QRect(230, 130, 161, 20))
        self.le_nombre_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:10px")
        self.le_nombre_2.setObjectName("le_nombre_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 90, 121, 20))
        self.label_5.setStyleSheet("border-radius:10px")
        self.label_5.setObjectName("label_5")
        self.le_nombre_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_nombre_3.setGeometry(QtCore.QRect(530, 90, 161, 20))
        self.le_nombre_3.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:10px")
        self.le_nombre_3.setObjectName("le_nombre_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">BUSQUEDA DE PERSONAL REGISTRADO</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">NOMBRE</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "ACTIVAR FILTRO"))
        self.pushButton_2.setText(_translate("MainWindow", "REGRESAR"))
        self.pushButton_3.setText(_translate("MainWindow", "SALIR"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">ACTIVE EL FILTRO Y POSTERIORMENTE INGRESE LA PALABRA A BUSCAR</span></p></body></html>"))
        self.pb_guardar.setText(_translate("MainWindow", "GUARDAR"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">DNI</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">DNI</p></body></html>"))
def guardar(self):
    df = pd.read_csv('Busqueda.csv')
    n = self.le_nombre.text()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
