# Form implementation generated from reading ui file 'Mensajedeentradaalsistema.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Bienvenido(object):
    def setupUi(self, Bienvenido):
        Bienvenido.setObjectName("Bienvenido")
        Bienvenido.resize(416, 139)
        Bienvenido.setMinimumSize(QtCore.QSize(416, 0))
        Bienvenido.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 78, 12, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label = QtWidgets.QLabel(parent=Bienvenido)
        self.label.setGeometry(QtCore.QRect(30, 30, 331, 20))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=Bienvenido)
        self.pushButton.setGeometry(QtCore.QRect(150, 70, 111, 31))
        self.pushButton.setStyleSheet("border-radius:10px")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Bienvenido)
        QtCore.QMetaObject.connectSlotsByName(Bienvenido)

    def retranslateUi(self, Bienvenido):
        _translate = QtCore.QCoreApplication.translate
        Bienvenido.setWindowTitle(_translate("Bienvenido", "Dialog"))
        Bienvenido.setToolTip(_translate("Bienvenido", "<html><head/><body><p><br/></p></body></html>"))
        Bienvenido.setWhatsThis(_translate("Bienvenido", "<html><head/><body><p>Bienvenido/a</p></body></html>"))
        self.label.setText(_translate("Bienvenido", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Bienvenido al sistema de Team Fortran!</span></p></body></html>"))
        self.pushButton.setText(_translate("Bienvenido", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bienvenido = QtWidgets.QDialog()
    ui = Ui_Bienvenido()
    ui.setupUi(Bienvenido)
    Bienvenido.show()
    sys.exit(app.exec())
